/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Vérifie l'opérabilité de l'API.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Représentation publique d'un compte enseignant (réponse API).
         *     Ne contient JAMAIS de champ sensible (mot de passe, hash, secrets).
         */
        Teacher: {
            /**
             * Format: uuid
             * @description Identifiant UUID v4 unique de l'enseignant
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id: string;
            /**
             * Format: email
             * @description Adresse email de l'enseignant (servant aussi de login)
             * @example marie.dupont@academie-versailles.fr
             */
            email: string;
            /**
             * @description Nom affiché choisi par l'enseignant
             * @example Marie Dupont
             */
            display_name: string;
            /**
             * @description Statut du compte :
             *     - `pending` : compte créé mais email non confirmé (Story 1.3)
             *     - `active` : compte confirmé et utilisable
             * @enum {string}
             */
            status: "pending" | "active";
            /**
             * Format: date-time
             * @description Horodatage ISO 8601 UTC de création
             * @example 2026-05-19T08:30:00Z
             */
            created_at: string;
            /**
             * Format: date-time
             * @description Horodatage ISO 8601 UTC de dernière modification
             * @example 2026-05-19T08:30:00Z
             */
            updated_at: string;
        };
        Error: {
            error: {
                /**
                 * @description Code erreur SCREAMING_SNAKE (ex. ACCESS_EXPIRED)
                 * @example ACCESS_EXPIRED
                 */
                code: string;
                /**
                 * @description Message lisible côté client
                 * @example L'accès a expiré.
                 */
                message: string;
                /** @description Détails optionnels (champ, contraintes, etc.) */
                details?: {
                    [key: string]: unknown;
                };
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service opérationnel */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status: string;
                    };
                };
            };
        };
    };
}
