/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Vérifie l'opérabilité de l'API.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inscription d'un nouvel enseignant
         * @description Crée un compte enseignant en statut `pending` et envoie de façon
         *     asynchrone un email de confirmation contenant un lien vers
         *     `GET /api/v1/auth/verify-email`. Le compte n'est activable qu'après
         *     clic sur ce lien (TTL 24 h).
         *
         *     Rate-limité par IP (FR-43, défaut `10/minute`).
         */
        post: operations["registerTeacher"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Confirmation de l'email d'un enseignant via token
         * @description Active le compte enseignant si le token (TTL 24 h) est valide.
         *     Aucune authentification requise — le lien est porteur d'un secret
         *     court-terme stocké en clair côté serveur.
         */
        get: operations["verifyTeacherEmail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Représentation publique d'un compte enseignant (réponse API).
         *     Ne contient JAMAIS de champ sensible (mot de passe, hash, secrets).
         */
        Teacher: {
            /**
             * Format: uuid
             * @description Identifiant UUID v4 unique de l'enseignant
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id: string;
            /**
             * Format: email
             * @description Adresse email de l'enseignant (servant aussi de login)
             * @example marie.dupont@academie-versailles.fr
             */
            email: string;
            /**
             * @description Nom affiché choisi par l'enseignant
             * @example Marie Dupont
             */
            display_name: string;
            /**
             * @description Statut du compte :
             *     - `pending` : compte créé mais email non confirmé (Story 1.3)
             *     - `active` : compte confirmé et utilisable
             * @enum {string}
             */
            status: "pending" | "active";
            /**
             * Format: date-time
             * @description Horodatage ISO 8601 UTC de création
             * @example 2026-05-19T08:30:00Z
             */
            created_at: string;
            /**
             * Format: date-time
             * @description Horodatage ISO 8601 UTC de dernière modification
             * @example 2026-05-19T08:30:00Z
             */
            updated_at: string;
        };
        /** @description Requête d'inscription d'un enseignant (email + mot de passe). */
        RegisterRequest: {
            /**
             * Format: email
             * @description Adresse email de l'enseignant — servira d'identifiant
             * @example marie.dupont@academie-versailles.fr
             */
            email: string;
            /**
             * @description Mot de passe en clair (la requête DOIT être en HTTPS en prod).
             *     Politique MVP : 12 caractères minimum, pas de règle de complexité.
             *     **Limite haute : 72 octets UTF-8** (limite intrinsèque de bcrypt —
             *     au-delà, les octets supplémentaires seraient silencieusement
             *     tronqués ; nous rejetons explicitement pour éviter toute
             *     ambiguïté côté authentification).
             * @example motdepasse123456
             */
            password: string;
        };
        /** @description Réponse de création d'un compte enseignant (statut initial `pending`). */
        TeacherCreated: {
            /**
             * Format: uuid
             * @description Identifiant UUID v4 du compte créé
             */
            id: string;
            /**
             * Format: email
             * @description Adresse email confirmée du compte
             */
            email: string;
            /**
             * @description Toujours `pending` à l'inscription — en attente de confirmation email
             * @enum {string}
             */
            status: "pending";
        };
        Error: {
            error: {
                /**
                 * @description Code erreur SCREAMING_SNAKE (ex. ACCESS_EXPIRED)
                 * @example ACCESS_EXPIRED
                 */
                code: string;
                /**
                 * @description Message lisible côté client
                 * @example L'accès a expiré.
                 */
                message: string;
                /** @description Détails optionnels (champ, contraintes, etc.) */
                details?: {
                    [key: string]: unknown;
                };
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service opérationnel */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status: string;
                    };
                };
            };
        };
    };
    registerTeacher: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Compte créé, email de confirmation envoyé */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeacherCreated"];
                };
            };
            /** @description Email déjà utilisé par un autre compte */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Données invalides (email malformé, mot de passe trop court, etc.) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Trop de requêtes (rate limit dépassé) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    verifyTeacherEmail: {
        parameters: {
            query: {
                /**
                 * @description Token de vérification reçu par email (43 caractères URL-safe en
                 *     émission ; aucune contrainte de longueur stricte côté contrat —
                 *     tout token non reconnu côté serveur est mappé à 400
                 *     `INVALID_OR_EXPIRED_TOKEN`).
                 */
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Email confirmé avec succès, compte activé */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Email confirmé. */
                        message: string;
                    };
                };
            };
            /**
             * @description Token invalide, inconnu, malformé ou expiré (toutes ces variantes
             *     sont indistinguables côté client — cf. AC4).
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
